### ISSUE TITLE
Badge (+ rating?)

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/openapi.tools#111]
Awesome Ruby have this little badge that folks can put on their README, which benefits them and the awesome ruby project. 

https://github.com/markets/awesome-ruby

We should look into doing something similar.

**Comment by matthewtrask** [comment]
You want to create our own little badge, or get added to this list?

**Comment by philsturgeon** [comment]
Man I suck at words sometimes. 

I want to create a badge scheme similar to this, and maybe even get ratings. It could be a default badge, then bronze, silver and gold as extra awards for tools we know are dope.

**Comment by matthewtrask** [comment]
@mbifulco how much work would it be to create badges?

**Comment by AndrewWalsh** [comment]
Five years have passed since this discussion, quite a fair bit of time. Appreciate this may have been on the backburner, but with a new site in view I would suggest closing this now and recalling it later.
