### ISSUE TITLE
The category on Converts seems to be incorrect

### ISSUE THREAD

**Issue by peter279k** [apisyouwonthate/openapi.tools#135]
As we can look at the `Converts` section on [openapi.tools](https://openapi.tools/).

And we can look it has the `GitHub` column name on this various tool table.

And we can notice that the `OpenAPI validator - Library that checks response against OpenAPI schema, based on request path and method` is not the GitHub repository.

And the repository link is available on `GitLab`.

To resolve this issue, I think we can consider adding the `GitLab` column on this table and add the `GitLab` logo to link GitLab repository link that it's like `GitHub` that.

And it will not let developers misunderstand the repository link and logo on front-end page :).

**Comment by matthewtrask** [comment]
I don't know what you mean by the converts section is incorrect, can you give me more detail please?
