### ISSUE TITLE
Add WAPIml

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/openapi.tools#142]
> @philsturgeon thanks for reaching out. We appreciate your interest in listing our tool in [OpenAPI.Tools](https://openapi.tools/). The support for OpenAPI v3.0 is in progress. [We already have a metamodel for OpenAPI v3](https://github.com/opendata-for-all/openapi-metamodel/tree/OpenAPI3) and we will integrate it soon into the tool.

https://github.com/opendata-for-all/wapiml/issues/17#issuecomment-539925964

**Comment by AndrewWalsh** [comment]
Wapiml is now archived, so will close this one https://github.com/opendata-for-all/wapiml
