### ISSUE TITLE
Column for OpenAPI 3.1

### ISSUE THREAD

**Issue by theletterf** [apisyouwonthate/openapi.tools#245]
OpenAPI 3.1 is already here, but support is a bit of a hit and miss.

https://lornajane.net/posts/2020/whats-new-in-openapi-3-1

It would be nice to add a column for OpenAPI 3.1 support.

**Comment by philsturgeon** [comment]
Well... it’s still RC not final, but sure let’s start tracking it!

**Comment by waldyrious** [comment]
@philsturgeon did you mean to close the issue? Your comment seems to convey the opposite intention :)

**Comment by philsturgeon** [comment]
Look at the website, it’s done.

**Comment by waldyrious** [comment]
Oh haha sorry, I totally missed it. For future reference, that was done in commit 70042a16b.
