### ISSUE TITLE
Add Akita

### ISSUE THREAD

**Issue by jlucktay** [apisyouwonthate/openapi.tools#257]
Monitors your API traffic and auto-generates an OpenAPI spec; can let you know, for example, if there is a breaking change between builds on your PRs.

https://www.akitasoftware.com

**Comment by captn3m0** [comment]
https://github.com/dcarr178/har2openapi also does something similar (akita is cloud-based, har2openapi works locally).

This might need a new section.

**Comment by philsturgeon** [comment]
I'd love a pull requesst adding "Auto-Generate" as a categoy, with Akita and har2openapi both added. 

Would either of you be so kind?

**Comment by matthewtrask** [comment]
@philsturgeon https://github.com/apisyouwonthate/openapi.tools/pull/272

**Comment by daveshanley** [comment]
Is this still active? Was a PR ever created?

**Comment by philsturgeon** [comment]
It wasn't added but should be. I think "Learning" might be a better name than Auto-Generating in retrospect, but stick this wherever Optic went.

**Comment by philsturgeon** [comment]
It's been merged into Postman now anyhoo.
