### ISSUE TITLE
add RESTler fuzzer to data validators

### ISSUE THREAD

**Issue by marina-p** [apisyouwonthate/openapi.tools#261]
Hello,

I noticed that ApiFuzzer is listed under validation tools, and wanted to suggest also adding the RESTler fuzzer to the list: https://github.com/microsoft/restler-fuzzer 

RESTLER's description from the README: 

RESTler is the first stateful REST API fuzzing tool for automatically testing cloud services through their REST APIs and finding security and reliability bugs in these services. For a given cloud service with an OpenAPI/Swagger specification, RESTler analyzes its entire specification, and then generates and executes tests that exercise the service through its REST API.

**Comment by matthewtrask** [comment]
hey that sounds good, if you open a PR we will get it merged. thanks!
