### ISSUE TITLE
Add API Contractor VS code extension

### ISSUE THREAD

**Issue by deiteris** [apisyouwonthate/openapi.tools#265]
Hello👋

I would like to add the [API Contractor](https://github.com/deiteris/api-contractor/tree/master/extension) extension for Visual Studio Code that I'm working on. The extension uses [AML Language Server](https://github.com/aml-org/als) for validation, conversion and linting and [Mulesoft API Console](https://github.com/mulesoft/api-console) for visualization and trying out of OpenAPI 2.0/3.0 and RAML 0.8/1.0 API definitions.

Will it be ok if I create a PR and what category should I use?

**Comment by daveshanley** [comment]
Project looks abandoned?

**Comment by deiteris** [comment]
No, it isn't. It's just mostly in maintenance mode.

**Comment by daveshanley** [comment]
The category I would recommend this sits in would be 'Data Validators' and 'Text Editors'

**Comment by philsturgeon** [comment]
Haha I like the gusto on the reply but "Maintenance mode" suggests ongoing maintenance, and its been three years since anything happened here. We are cleaning deck for a new site build, but if you'd like this added I suggest a PR as the way to go.
