### ISSUE TITLE
add FastAPI as an auto generator

### ISSUE THREAD

**Issue by laundmo** [apisyouwonthate/openapi.tools#277]
The Python framework FastAPI will [automatically generate OpenAPI docs](https://fastapi.tiangolo.com/tutorial/first-steps/?h=openapi#check-the-openapijson) for the code you write, could this be added to the auto generator section?

**Comment by matthewtrask** [comment]
It can be, open a pull request and we will check it out :)

**Comment by AndrewWalsh** [comment]
Quite a fair few years have transpired since @matthewtrask 's requesst. Will close this for now, but his request remains open :).
