### ISSUE TITLE
Add swagger-request-validator

### ISSUE THREAD

**Issue by jfnavin** [apisyouwonthate/openapi.tools#279]
Hi,

It would be great to add [swagger-request-validator](https://bitbucket.org/atlassian/swagger-request-validator/src/master/)  

This project has been in development for ~5yrs and has support for Swagger 2.0 and OpenAPI 3.0.

Cheers,
James

**Comment by matthewtrask** [comment]
hey thanks!

However, we are trying our hardest to help move people off "swagger" and onto "openapi", hence the name of the project :)
