### ISSUE TITLE
Additional Tools 

### ISSUE THREAD

**Issue by mp3monster** [apisyouwonthate/openapi.tools#293]
Can I suggest https://apiary.io/ - with its live mock server and offers a free tier.  In addition to OAS, it also supports the API Blueprint standard. 

A lot of the foundations to Apiary have been made available as open-source, for example, Dredd test tool https://dredd.org/en/latest/

Considered a section for Visual Studio Code plugins ?

**Comment by drew-cooper** [comment]
Swashbuckle would also be good to add. Autogenerate OpenApi 2.0 and 3.0 from ASP.Net and ASP.Net Core code. Also provides Swagger UI hosted with your API.
* https://github.com/domaindrivendev/Swashbuckle.AspNetCore
* https://github.com/domaindrivendev/Swashbuckle.WebApi

**Comment by AndrewWalsh** [comment]
Given the years that have transpired since these discussions and the prospect of a new site that will revitalise the open.tools enterprise, I'll close this for now. However, I encourage re-submission when convenient, and thank you for raising this.
