### ISSUE TITLE
Testing category doesn't show up

### ISSUE THREAD

**Issue by jblazek** [apisyouwonthate/openapi.tools#30]
The data file has a link to a tool in the `testing` category, but this doesn't show up on the deployed website: http://openapi.tools.

https://github.com/apisyouwonthate/openapi.tools/blob/master/_data/tools.yml#L427

It looks like the category `testing` is case sensitive, and the data file uses the wrong case? Or maybe the website not continuously deployed?

**Comment by philsturgeon** [comment]
Seems to be showing up now! thanks for reporting this :)
