### ISSUE TITLE
connexion is a server generator for python, not a mock server

### ISSUE THREAD

**Issue by ddurham2** [apisyouwonthate/openapi.tools#318]
[Connexion](https://github.com/spec-first/connexion) is documented as a mock server, rather it aids in generating a server, calling a method with the name specified in the openapi for each endpoint, only after all input validation, and optionally authentication, is automatically done for you.

https://github.com/apisyouwonthate/openapi.tools/blob/d916eca2a0d421c2ebe7973994dc172002ed3172/_data/tools.yml#L626

**Comment by philsturgeon** [comment]
So close to being a pull request! :D

**Comment by AndrewWalsh** [comment]
Yet to be seen, or perhaps it was, in any case, I'll close this with the admission that a PR request is always open.

**Comment by ddurham2** [comment]
how about the above?
