### ISSUE TITLE
Could you add Stoplight to your list?

### ISSUE THREAD

**Issue by K2ouMais** [apisyouwonthate/openapi.tools#319]
This is the tool of my choice when starting making an API.

I always choose design first and only after that I start developing my API.

It is a breeze to use Stoplight Studio as a free Standalone Software that already supports openAPI 3.1.

https://stoplight.io/studio

With Stoplight Elements you can even show your openAPI file as an awesome documentation on your webpage.

https://stoplight.io/open-source/elements

**Comment by philsturgeon** [comment]
Thanks for the suggestion! Elements. Studio, and Prism are all on the site already. 🙌🏻

**Comment by K2ouMais** [comment]
Ups... Sorry, didnt see it.

The URL of Stoplight Docs goes to a 404 error page.

**Comment by philsturgeon** [comment]
Fixed, thank you
