### ISSUE TITLE
Add version filter to the top of the page

### ISSUE THREAD

**Issue by nemani** [apisyouwonthate/openapi.tools#320]
There should be a version select to quickly filter out projects and tools that support a specific version of the OpenAPI Spec

**Comment by philsturgeon** [comment]
This site is built with Jekyll or this could be done with JavaScript. Either way if you'd like to take a swing that would be fantastic!

**Comment by daveshanley** [comment]
I think JS would be the easiest. Looks like a simple enough job.

**Comment by AndrewWalsh** [comment]
A new site is forthcoming, and its capacities open new doors. @nemani on such occasion your re-submission of a PR would be highly appreciated.
