### ISSUE TITLE
tooling list update: openapi and json schema validators in Perl

### ISSUE THREAD

**Issue by karenetheridge** [apisyouwonthate/openapi.tools#337]
- a JSON Schema evaluator (draft7, draft2019-09, draft2020-12) - https://github.com/karenetheridge/JSON-Schema-Modern, https://metacpan.org/pod/JSON::Schema::Modern
- an OpenAPI request/response validator (only v3.1 supported, not v3.0) - https://github.com/karenetheridge/OpenAPI-Modern, https://metacpan.org/pod/OpenAPI::Modern

**Comment by daveshanley** [comment]
Please submit a PR.
