### ISSUE TITLE
Category for tools such as Swashbuckle and Microsoft/OpenAPI.NET.Annotations

### ISSUE THREAD

**Issue by HappyTreesDev** [apisyouwonthate/openapi.tools#35]
I am not sure if there are other tools for different languages, but for c# I know of two tools that are used often to generate openapi documentation. They do not generate the code, but instead work with annotations or comments to generate the json document for openapi.

I think it would be nice to have a category for this but I am not sure what that category would be called. Maybe Document Generators.

**Comment by philsturgeon** [comment]
This annotations category, should it be added, would also include #57.

To reiterate a point I made in that issue, annotation based tools are using annotations to create specs, and then what you do with those specs is up to you. Commonly thats documentation, but that doesn't mean they're documentation generators. 

Annotations > Specs > Docs
Annotations > Specs > Mocks
Annotations > Specs > Contract Tests
Annotations > Specs > SDKs

See what I mean? 

I could add an Annotations category, but... I f**king hate the code-first approach to OpenAPI for a shopping list of reasons.

**Comment by philsturgeon** [comment]
Here are a bunch of annotations we could add https://swagger.io/blog/api-development/swagger-annotation-libraries/

**Comment by matthewtrask** [comment]
Im going to close this for now as there hasn't been any activity from the OP in over a year.
