### ISSUE TITLE
Update documentation/redoc to include support for oas3

### ISSUE THREAD

**Issue by jblazek** [apisyouwonthate/openapi.tools#38]
ReDoc now supports OAS v3, the linked blocking issue is also closed.

https://github.com/Rebilly/ReDoc#roadmap

**Comment by philsturgeon** [comment]
It's closed, but it's still in alpha. Until ReDoc v2 final is out, I feel funny about saying it supports OpenAPI v3.0, even though support is really good.

**Comment by philsturgeon** [comment]
Relevant https://github.com/apisyouwonthate/openapi.tools/pull/23
