### ISSUE TITLE
How are PR reviews done on this repo? 

### ISSUE THREAD

**Issue by spacether** [apisyouwonthate/openapi.tools#399]
How are PR reviews done on this repo?
can some clarification be added on it?
Can PRs be reviewed within a certain window of filing like 1 to 2 months?

At the time of writing this issue there is a PR open which was written in 2019. Seeking understanding and an answer to set expectations here. Thanks!

**Comment by daveshanley** [comment]
Hello. Things got a little quiet around here for a while. I am here to help now. 

You can expect a response within a few working days moving forward.
