### ISSUE TITLE
Add Kubb

### ISSUE THREAD

**Issue by stijnvanhulle** [apisyouwonthate/openapi.tools#415]
Hi,

I make a tool that converts **OpenAPI** to TypeScript, React-Query, Zod, Zodios and Axios. It's called [Kubb](https://github.com/kubb-project/kubb) and our website is the following: https://github.com/kubb-project/kubb

Can I recommend it to your list?

**Comment by daveshanley** [comment]
Yes you can!

**Comment by stijnvanhulle** [comment]
https://github.com/apisyouwonthate/openapi.tools/pull/416
