### ISSUE TITLE
Add ExpressO

### ISSUE THREAD

**Issue by souhailaS** [apisyouwonthate/openapi.tools#451]
https://www.npmjs.com/package/expresso-api?activeTab=readme

https://github.com/AlessandroRomanelli/ExpressO

A CLI to automatically generate OAS 3.0 from Express.js backends code.

**Comment by philsturgeon** [comment]
Thanks for this! If you send a PR I'll be reviewing them much more quickly now.

**Comment by AndrewWalsh** [comment]
Following @philsturgeon 's comment, a PR would be highly appreciated and a new issue can be opened at any time. Closing this now, but please do reopen @souhailaS once prior comments are addressed.
