### ISSUE TITLE
Big breaking change: sort yaml entries by name

### ISSUE THREAD

**Issue by rafalkrupinski** [apisyouwonthate/openapi.tools#478]
Sorting entries in the yaml file by (case-insensitive) name would greatly reduce merge conflicts.

One problem - existing PRs would need to be updated.

**Comment by philsturgeon** [comment]
I appreciate the suggestion but the new version of the site will hopefully use individual files for each tool so we dont constantly struggle with conflicts. 

@mbifulco not sure if this has been mentioned as a requirement elsewhere but lets make sure we do it. most static site generators support this.
