### ISSUE TITLE
Update openapi-json-schema-genrator to show that java is supported

### ISSUE THREAD

**Issue by spacether** [apisyouwonthate/openapi.tools#492]
Update openapi-json-schema-geenrator to show that java is supported
Will be closed by: https://github.com/apisyouwonthate/openapi.tools/pull/483

**Comment by AndrewWalsh** [comment]
I see that https://github.com/apisyouwonthate/openapi.tools/pull/483 was merged, do I'll close this issue. Thanks @spacether .
