### ISSUE TITLE
No link to specifications

### ISSUE THREAD

**Issue by skecskes** [apisyouwonthate/openapi.tools#5]
Great stuff, I just didn't find out what open Api is. Link to openApi specifications doesn't work. Thanks

![screenshot from 2018-01-12 23-36-04](https://user-images.githubusercontent.com/3411329/34899549-8d359098-f7f1-11e7-8c5d-83167dad4b42.png)

**Comment by matthewtrask** [comment]
Fixed, thanks for catching it!
