### ISSUE TITLE
Add openapi-ts - Hey API

### ISSUE THREAD

**Issue by jellydn** [apisyouwonthate/openapi.tools#500]
# What

Add https://heyapi.vercel.app/welcome.html

# Why

Openapi-ts is a fork of openapi-typescript-codegen, refer https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1276#issuecomment-1302392146

**Comment by AndrewWalsh** [comment]
The welcome screen is returning a 404 for me:

<img width="953" alt="Screenshot 2024-05-15 at 01 47 30" src="https://github.com/apisyouwonthate/openapi.tools/assets/15863952/1b5d72ab-d075-44df-8e21-bd874d61b181">

**Comment by jellydn** [comment]
> The welcome screen is returning a 404 for me:
> 
> <img alt="Screenshot 2024-05-15 at 01 47 30" width="953" src="https://private-user-images.githubusercontent.com/15863952/330557093-1b5d72ab-d075-44df-8e21-bd874d61b181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzAxNzcsIm5iZiI6MTcxNTcyOTg3NywicGF0aCI6Ii8xNTg2Mzk1Mi8zMzA1NTcwOTMtMWI1ZDcyYWItZDA3NS00NGRmLThlMjEtYmQ4NzRkNjFiMTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDIzMzc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMTBkNDljY2E4MjcxYWU0YmY1ZTNiNjViMzQ1OTVhNDFmZTlhMDMxZWIwYjMzYjUyOTA1MzlhM2VmN2YwNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uPsXWNmhicR8Nh7VMxiMPN3nrZy8UOHMknZuGlrpLIs">

Here you are https://heyapi.vercel.app/

**Comment by AndrewWalsh** [comment]
This looks cool, can you point to the PR this pertains to for https://github.com/hey-api/openapi-ts ?

**Comment by AndrewWalsh** [comment]
@jellydn Could you please raise a PR for this? The goal in general is that contributors create PRs. You've raised an interesting project that clearly has a userbase and aligns with contributor guidelines. If you could raise a PR for this I/we'd be happy to review, and thanks for raising this.

**Comment by jellydn** [comment]
Let me close this issue. I thought that when I added a tool then maintainer will review and consider to add to the website or not.
