### ISSUE TITLE
Add category descriptions

### ISSUE THREAD

**Issue by LarBearrr** [apisyouwonthate/openapi.tools#51]
We need to add descriptions to categories and add them to the site.

- Descriptions can be added in the [categories.yml](https://github.com/apisyouwonthate/openapi.tools/blob/master/_data/categories.yml) file
- Include 2-3 sentences for each description
- Display the description underneath the category title on the page

**Comment by matthewtrask** [comment]
@lornajane made a wonderful PR which closes this via https://github.com/apisyouwonthate/openapi.tools/pull/131
