### ISSUE TITLE
Phil's Dumping Ground of Tools to Add

### ISSUE THREAD

**Issue by philsturgeon** [apisyouwonthate/openapi.tools#517]
Mid rampage on various other things but these came up and I'd like them to be added if anyone has a minute. 

- [OpenAPI Preview](https://marketplace.visualstudio.com/items?itemName=zoellner.openapi-preview) by Andreas Zoellner - Preview panel using Stoplight Elements.
- [OpenAPI Viewer](https://marketplace.visualstudio.com/items?itemName=AndrewButson.vscode-openapi-viewer)by Andrew Butson - Preview panel using RapiDoc.

**Comment by AndrewWalsh** [comment]
@philsturgeon I've two PRs on that end:

OpenAPI Viewer https://github.com/apisyouwonthate/openapi.tools/pull/520

OpenAPI Preview https://github.com/apisyouwonthate/openapi.tools/pull/519
