### ISSUE TITLE
Split “Validator” into “Data validator” and “Schema validator”

### ISSUE THREAD

**Issue by boyanyordanov** [apisyouwonthate/openapi.tools#52]
From chat: 
One ensures the Schema itself is valid, the other ensures data is valid against that Schema. They’re RARE.

**Comment by boyanyordanov** [comment]
@philsturgeon I suppose this is the "Parsers/Validators" category and we're making 2 (or 3?) new categories now? 

Do libraries that can parse a spec count as validators here ?  

Also to check if my understanding is correct here: 

- Schema validator - ensures the Schema itself is valid
- Data validator - ensures data is valid against that Schema

**Comment by philsturgeon** [comment]
I think we’d want to have:

- Parsers 
- Schema Validators
- Data Validators

Parsers just help folks walk and navigate through the tree, which is a very different goal from a validator, which may depend on a third party parser, or bundle it’s own parser functionality.

**Comment by philsturgeon** [comment]
I think my definition of Schema Validators is what you're thinking of when you say "OAS schema instance (request/response) validators", which means im not sure what your definition of 
"OAS schema validator" is.

**Comment by MikeRalphson** [comment]
The latter would just validate that a schema object was valid OAS JSON schema subset/superset. Not sure if that's even a thing.

**Comment by philsturgeon** [comment]
Oh. Yeah those things don't exist and I'm not too worried about finding any. The schema object is valid if the OpenAPI document as a whole is valid, right?

**Comment by MikeRalphson** [comment]
Yes, I guess people who put their OAS schema objects in separate files can / do resolve before validating.

**Comment by boyanyordanov** [comment]
In a broad sense those still relate to validating OAS documents and since there aren’t any specifically for schema objects at the moment, I think it will be fine to place them in the same category.
I’ll prepare a PR with the 3 Phil defined above and submit it sometime tomorrow.

**Comment by philsturgeon** [comment]
Done in #54, thank you!
